export const sliderItems = [
  {
    id: 1,
    img: "https://i.discogs.com/TjduV57Rd-RjXuGgk0LyOL9jZ_xL-sxYGsyTI0i2aHI/rs:fit/g:sm/q:90/h:593/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMzOTAx/OS0xNDI3NzgzNzM2/LTEyMDQuanBlZw.jpeg",
    artist: "Janet Jackson",
    link: "https://www.discogs.com/sell/release/339019?seller=piknik1979",
    desc: "Control",
    bg: "f5fafd",
  },
  {
    id: 2,
    img: "https://i.discogs.com/kXe5dxTZZmGvaXff3I7fA97JUq-FFpV9SBlfBvDaMcA/rs:fit/g:sm/q:90/h:602/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM4NTg2/My0xMTg4NjY2MjI3/LmpwZWc.jpeg",
    artist: "BLITZ!",
    desc: "Voice of a Generation",
    bg: "fcf1ed",
  },
  {
    id: 3,
    img: "https://i.discogs.com/rYNfIA9eW_j-ASaP3lHPCAOU0_iujo7347VWgeA5eQM/rs:fit/g:sm/q:90/h:615/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI0NjU1/MTMtMTU0NDg3NDk3/Mi0xNzc5LmpwZWc.jpeg",
    artist: "Jesus Jones",
    desc: "Real Real Real",
    link: "https://www.discogs.com/sell/item/3381537480",
    bg: "fbf0f4",
  },
];

export const categories = [
  {
    id: 1,
    img: "https://i.discogs.com/YgdNqtVFodiwBmV8CmLuJoYHo34FIEg9gF5YI7bGWi8/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE3MzQ2/NzItMTM2NTI3MzI4/MC0xNzQ3LmpwZWc.jpeg",
    genre: "STAGE AND SCREEN",
  },
  {
    id: 2,
    img: "https://i.discogs.com/B31cy3fwI32K4getyz0PtrVb5h2TgOV-AkLf3U4Ui7c/rs:fit/g:sm/q:90/h:599/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI5NjYy/MjU4LTE3MDY3ODky/MzYtOTE1Mi5qcGVn.jpeg",
    genre: "SOUL AND FUNK",
  },
  {
    id: 3,
    img: "https://i.discogs.com/nep7SameqEH5oVPS4IEOzb1zg0LJ4Zy8e5IbPIVaNvg/rs:fit/g:sm/q:90/h:612/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwNDQy/NjUtMTQ3NTYwNTU5/OC04ODM5LmpwZWc.jpeg",
    genre: "PUNK & OI",
  },
  {
    id: 4,
    img: "https://i.discogs.com/KAj0qfL9hrHki4UPiPCu8ZzpHr-h7g6qUlNvgFBOLBk/rs:fit/g:sm/q:90/h:601/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExMDQz/NzA0LTE2OTcyMzIy/NTEtOTYwNi5qcGVn.jpeg",
    genre: "JAZZ",
  },
];

export const popularProducts = [
  {
    id: 1,
    img: "https://i.discogs.com/vHguFUhuZFZtnXHg_jE4X3WaFoy1Nkm5wWKjJizAtHQ/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTc3ODc2/Mi0xNDEzMTQ5MjEy/LTg3NTMuanBlZw.jpeg",
    link: "https://www.discogs.com/sell/release/778762?seller=piknik1979",
    desc: "10CC The Original Soundtrack",
    genre: "POPROCK",
  },
  {
    id: 2,
    img: "https://i.discogs.com/DRwG04BJltbySNY51aUPY9oUxq1dnjDqlHyLJ3ULPpA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI0MDEy/Ni0xNzE2NzgwMzQ0/LTExMDAuanBlZw.jpeg",
    link: "https://www.discogs.com/sell/release/240126?seller=piknik1979",
    desc: "2 Unlimited – Workaholic",
    genre: "ELECTRONIC",
  },
  {
    id: 3,
    img: "https://i.discogs.com/Rf-5XxqkkUct0zWvPiEywCu3EArLLjYHK7gYQBCsxxg/rs:fit/g:sm/q:90/h:507/w:500/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExODY1/MzItMTIxMTAzMzk1/OC5qcGVn.jpeg",
    link: "https://www.discogs.com/sell/release/1186532?seller=piknik1979",
    desc: "The Original London Cast - Hair",
    genre: "STAGE & SCREEN",
  },
  {
    id: 4,
    img: "https://i.discogs.com/McwnBicQQDA0GWOBy-u-tsfNwPiaIN9gNVEJ_84FngM/rs:fit/g:sm/q:90/h:584/w:582/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQzMTcx/MC0xMjg2NjM2MzM0/LmpwZWc.jpeg",
    link: "https://www.discogs.com/sell/item/1287233505?ev=bp_img",
    genre: "POPROCK",
  },
  {
    id: 5,
    img: "https://i.discogs.com/P0uOFAF6hEePgknjJSW3gAtyYJVA6yX05A4N1-tUGKI/rs:fit/g:sm/q:90/h:409/w:412/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIxODkw/Ny0xMTQ0MjMwMDcw/LmpwZWc.jpeg",
    genre: "STAGE & SCREEN",
  },
  {
    id: 6,
    img: "https://i.discogs.com/eJfi2vgqw43VKNVAWOpIpyQk-hS1GCS3syucDti8BaA/rs:fit/g:sm/q:90/h:602/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTc2NTUy/NjItMTQ0NjA0OTk0/MC0zNTU2LmpwZWc.jpeg",
    genre: "STAGE & SCREEN",
  },
  {
    id: 7,
    img: "https://i.discogs.com/ZWn5RfkMMWx__31GGexf_cKSq3JJP3-UAEbj6cV8Hyc/rs:fit/g:sm/q:90/h:493/w:500/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQwMjU1/NzItMTM1MzkzNjI0/OC05MTM5LmpwZWc.jpeg",
    genre: "POPROCK",
  },
  {
    id: 8,
    img: "https://i.discogs.com/uMF0FOiy7TLNFZ7U1HFsv80femAebMI54b27zlLPL-I/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI5NjYy/MjU4LTE3MDY3ODky/NDctOTc0NC5qcGVn.jpeg",
    link: "https://www.discogs.com/sell/item/3348405201?ev=bp_det",
    album: "10CC The Original Soundtrack",
    genre: "POPROCK",
    media: "Very Good Plus",
    sleeve: "Fair",
    price: "$45",
  },
  {
    id: 9,
    img: "https://i.discogs.com/u3TINXMaJaVRObGEMY4clwYuQnu13SGGZIt5MJCbRV0/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTU4OTUx/Mi0xMTM1MzgwOTA0/LmpwZWc.jpeg",
    link: "https://www.discogs.com/sell/item/3381537480",
    album: "Cyndi Lauper - I Drove All Night",
    genre: "SYNTHPOP",
    media: "Near Mint",
    sleeve: "VG+",
    price: "£4.95",
  },
  {
    id: 10,
    img: "https://i.discogs.com/NsEdQcVMz-RJ2MoiNRQCrG8UtaQF2JVidpOFTX7FFGY/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI0NjU1/MTMtMTU0NDg3NDk3/Mi0xNzc5LmpwZWc.jpeg",
    link: "https://www.discogs.com/sell/item/3381537480?ev=bp_det",
    album: "Jesus Jones - Real Real Real",
    genre: "POPROCK",
    media: "VG+",
    sleeve: "VG+",
    price: "£2.90",
  },
  {
    id: 11,
    img: "https://i.discogs.com/iMARajX9D8WtiKGKDb2jIXI7Y5wyCwJqhOkVJEEt7M4/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE4MjIz/MTktMTcyMDAyOTUz/My0zNzcyLmpwZWc.jpeg",
    link: "https://www.discogs.com/sell/item/3381536061?ev=bp_det",
    album: "Status Quo - Blue For You",
    genre: "POPROCK",
    media: "VG+",
    sleeve: "VG",
    price: "£2.89",
  },
  {
    id: 12,
    img: "https://i.discogs.com/MvdqH5poE-mZ-b2ASUnKwb5DmXhxGY0zW_wqbDQL4nc/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEzNzYw/NzQtMTM5MTg3MzU3/MS03OTg1LmpwZWc.jpeg",
    link: "https://www.discogs.com/sell/item/3361455171?ev=bp_det",
    album: "Shakin' Stevens And The Sunsets - Shakin' Stevens And The Sunsets",
    genre: "ROCK N ROLL",
    media: "VG+",
    sleeve: "VG",
    price: "£1.99",
  },
  {
    id: 13,
    img: "https://i.discogs.com/RO04Zr0gK95cXYaJ3tDnDgj3j46E6QkZlSKUHykjxXY/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3NjMx/MC0xNTExNzE1MjM5/LTY3NzEuanBlZw.jpeg",
    link: "https://www.discogs.com/sell/item/3361454538?ev=bp_det",
    album: "Michael Jackson And Diana Ross - Love Songs",
    genre: "SOUL & FUNK",
    media: "VG+",
    sleeve: "VG",
    price: "£2.22",
  },
  {
    id: 14,
    img: "https://i.discogs.com/hmhEXTXoFyK6EOQsurmkp6e_eJK9jRXYAqTSEkOFlQ8/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExNDQz/NTUtMTI5NjczNjA3/NC5qcGVn.jpeg",
    link: "https://www.discogs.com/sell/item/3361453377?ev=bp_det",
    album: "Stiff Little Fingers - Nobody's Heroes",
    genre: "PUNK",
    media: "VG",
    sleeve: "VG+",
    price: "£19.99",
  },
  {
    id: 15,
    img: "https://i.discogs.com/AaxubAHJor5e3XgZaDqCQFLPrCHbuDUy5voldoHdGeY/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM0MDQ4/NzMtMTY1MzQ3Nzg2/NC05MTk0LmpwZWc.jpeg",
    link: "https://www.discogs.com/sell/item/3361451739?ev=bp_det",
    album: "The Shadows - At Their Very Best",
    genre: "POPROCK",
    media: "NM",
    sleeve: "VG+",
    price: "£3.90",
  },

  // {
  //   id: 8,
  //   img: "https://i.discogs.com/JUPEfbNYwMXq385v3XUUrCnhR8HgeWeAQaXHbDTr_g4/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE3ODkx/MS0xMzczNDg4MzE2/LTMwMDkuanBlZw.jpeg",
  //   genre: "",
  // },
  // {
  //   id: 9,
  //   img: "https://i.discogs.com/h7yGdT_Bca4rJee4EEad_xoRKJrFmAejvsnpkDk0KGE/rs:fit/g:sm/q:90/h:607/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ4NjUx/MDItMTU0MjYzOTk3/OS02MDMxLmpwZWc.jpeg",
  //   genre: "",
  // },
];
