export const sliderItems = [
  {
    id: 1,
    img: "https://i.discogs.com/TjduV57Rd-RjXuGgk0LyOL9jZ_xL-sxYGsyTI0i2aHI/rs:fit/g:sm/q:90/h:593/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMzOTAx/OS0xNDI3NzgzNzM2/LTEyMDQuanBlZw.jpeg",
    artist: "Janet Jackson",
    link: "https://www.discogs.com/sell/release/339019?seller=piknik1979",
    desc: "Control",
    bg: "f5fafd",
  },
  {
    id: 2,
    img: "https://i.discogs.com/kXe5dxTZZmGvaXff3I7fA97JUq-FFpV9SBlfBvDaMcA/rs:fit/g:sm/q:90/h:602/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM4NTg2/My0xMTg4NjY2MjI3/LmpwZWc.jpeg",
    artist: "BLITZ!",
    desc: "Voice of a Generation",
    bg: "fcf1ed",
  },
  {
    id: 3,
    img: "https://i.discogs.com/rYNfIA9eW_j-ASaP3lHPCAOU0_iujo7347VWgeA5eQM/rs:fit/g:sm/q:90/h:615/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI0NjU1/MTMtMTU0NDg3NDk3/Mi0xNzc5LmpwZWc.jpeg",
    artist: "Jesus Jones",
    desc: "Real Real Real",
    link: "https://www.discogs.com/sell/item/3381537480",
    bg: "fbf0f4",
  },
];

export const categories = [
  {
    id: 1,
    img: "https://i.discogs.com/YgdNqtVFodiwBmV8CmLuJoYHo34FIEg9gF5YI7bGWi8/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE3MzQ2/NzItMTM2NTI3MzI4/MC0xNzQ3LmpwZWc.jpeg",
    genre: "Stage & Screen",
    media: "Near Mint",
    sleeve: "Very Good+",
    price: "£3.90",
  },
  {
    id: 2,
    img: "https://i.discogs.com/B31cy3fwI32K4getyz0PtrVb5h2TgOV-AkLf3U4Ui7c/rs:fit/g:sm/q:90/h:599/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI5NjYy/MjU4LTE3MDY3ODky/MzYtOTE1Mi5qcGVn.jpeg",
    genre: "Funk & Soul",
  },
  {
    id: 3,
    img: "https://i.discogs.com/nep7SameqEH5oVPS4IEOzb1zg0LJ4Zy8e5IbPIVaNvg/rs:fit/g:sm/q:90/h:612/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwNDQy/NjUtMTQ3NTYwNTU5/OC04ODM5LmpwZWc.jpeg",
    genre: "Punk",
  },
  {
    id: 4,
    img: "https://i.discogs.com/KAj0qfL9hrHki4UPiPCu8ZzpHr-h7g6qUlNvgFBOLBk/rs:fit/g:sm/q:90/h:601/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExMDQz/NzA0LTE2OTcyMzIy/NTEtOTYwNi5qcGVn.jpeg",
    genre: "Jazz",
  },
];

export const popularProducts = [
  {
    id: 1,
    img: "https://i.discogs.com/vHguFUhuZFZtnXHg_jE4X3WaFoy1Nkm5wWKjJizAtHQ/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTc3ODc2/Mi0xNDEzMTQ5MjEy/LTg3NTMuanBlZw.jpeg",
    link: "https://www.discogs.com/sell/release/778762?seller=piknik1979",
    genre: "Pop Rock",
    desc: "10cc - The Original Soundtrack (LP, album, Gat)",
    media: "Very Good+",
    sleeve: "Very Good",
    price: "£2.49",
  },
  {
    id: 2,
    img: "https://i.discogs.com/DRwG04BJltbySNY51aUPY9oUxq1dnjDqlHyLJ3ULPpA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI0MDEy/Ni0xNzE2NzgwMzQ0/LTExMDAuanBlZw.jpeg",
    link: "https://www.discogs.com/sell/release/240126?seller=piknik1979",
    desc: "2 Unlimited - Workaholic",
    genre: "Electronic",
    media: "Very Good+",
    sleeve: "Very Good+",
    price: "£1.49",
  },
  {
    id: 3,
    img: "https://i.discogs.com/Rf-5XxqkkUct0zWvPiEywCu3EArLLjYHK7gYQBCsxxg/rs:fit/g:sm/q:90/h:507/w:500/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExODY1/MzItMTIxMTAzMzk1/OC5qcGVn.jpeg",
    link: "https://www.discogs.com/sell/release/1186532?seller=piknik1979",
    desc: "The Original London Cast - Hair",
    genre: "Stage & Screen",
    media: "Near Mint",
    sleeve: "Near Mint",
    price: "£2.49",
  },
  {
    id: 4,
    img: "https://i.discogs.com/McwnBicQQDA0GWOBy-u-tsfNwPiaIN9gNVEJ_84FngM/rs:fit/g:sm/q:90/h:584/w:582/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQzMTcx/MC0xMjg2NjM2MzM0/LmpwZWc.jpeg",
    link: "https://www.discogs.com/sell/item/1287233505?ev=bp_img",
    desc: "Abba - The Visitors",
    genre: "Pop Rock",
    media: "Very Good",
    sleeve: "Very Good",
    price: "£2.49",
  },
  {
    id: 5,
    img: "https://i.discogs.com/P0uOFAF6hEePgknjJSW3gAtyYJVA6yX05A4N1-tUGKI/rs:fit/g:sm/q:90/h:409/w:412/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIxODkw/Ny0xMTQ0MjMwMDcw/LmpwZWc.jpeg",
    desc: "Adam F / DJ Fresh – The Original Junglesound E.P.",
    link: "https://www.discogs.com/sell/release/218907?seller=piknik1979",
    genre: "Electronic",
    media: "Near Mint",
    sleeve: "Generic",
    price: "£11.49",
  },
  {
    id: 6,
    img: "https://i.discogs.com/eJfi2vgqw43VKNVAWOpIpyQk-hS1GCS3syucDti8BaA/rs:fit/g:sm/q:90/h:602/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTc2NTUy/NjItMTQ0NjA0OTk0/MC0zNTU2LmpwZWc.jpeg",
    link: "https://www.discogs.com/sell/cart/?add=355435705&ev=",
    genre: "Stage & Screen",
    media: "Near Mint",
    sleeve: "Generic",
    price: "£11.49",
  },
  {
    id: 7,
    img: "https://i.discogs.com/ZWn5RfkMMWx__31GGexf_cKSq3JJP3-UAEbj6cV8Hyc/rs:fit/g:sm/q:90/h:493/w:500/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQwMjU1/NzItMTM1MzkzNjI0/OC05MTM5LmpwZWc.jpeg",
    link: "https://www.discogs.com/sell/item/2984728994?ev=bp_det",
    genre: "Hard Rock",
    media: "Very Good",
    sleeve: "Very Good",
    price: "£4.99",
  },
  {
    id: 8,
    img: "https://i.discogs.com/3DDgXarMNstkclpfMvOTqMVN3LY32pyyTjPPYVV7U_A/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTcxMzM5/OS0xMjU5MzY1NjM0/LmpwZWc.jpeg",
    link: "https://www.discogs.com/sell/item/3330968229?ev=bp_det",
    desc: "Gene Loves Jezebel - Discover (LP, Album)",
    genre: "Glam Rock",
    media: "Very Good Plus",
    sleeve: "Very Good",
    price: "£7.50",
  },
  {
    id: 9,
    img: "https://i.discogs.com/u3TINXMaJaVRObGEMY4clwYuQnu13SGGZIt5MJCbRV0/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTU4OTUx/Mi0xMTM1MzgwOTA0/LmpwZWc.jpeg",
    link: "https://www.discogs.com/sell/item/3381537480",
    desc: "Cyndi Lauper - I Drove All Night",
    genre: "Synth Pop",
    media: "Near Mint",
    sleeve: "Very Good+",
    price: "£4.95",
  },
  {
    id: 10,
    img: "https://i.discogs.com/NsEdQcVMz-RJ2MoiNRQCrG8UtaQF2JVidpOFTX7FFGY/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI0NjU1/MTMtMTU0NDg3NDk3/Mi0xNzc5LmpwZWc.jpeg",
    link: "https://www.discogs.com/sell/item/3381537480?ev=bp_det",
    desc: "Jesus Jones - Real Real Real",
    genre: "Pop Rock",
    media: "Very Good+",
    sleeve: "Very Good+",
    price: "£2.90",
  },
  {
    id: 11,
    img: "https://i.discogs.com/iMARajX9D8WtiKGKDb2jIXI7Y5wyCwJqhOkVJEEt7M4/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE4MjIz/MTktMTcyMDAyOTUz/My0zNzcyLmpwZWc.jpeg",
    link: "https://www.discogs.com/sell/item/3381536061?ev=bp_det",
    desc: "Status Quo - Blue For You",
    genre: "Pop Rock",
    media: "Very Good+",
    sleeve: "Very Good",
    price: "£2.89",
  },
  {
    id: 12,
    img: "https://i.discogs.com/MvdqH5poE-mZ-b2ASUnKwb5DmXhxGY0zW_wqbDQL4nc/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEzNzYw/NzQtMTM5MTg3MzU3/MS03OTg1LmpwZWc.jpeg",
    link: "https://www.discogs.com/sell/item/3361455171?ev=bp_det",
    desc: "Shakin' Stevens And The Sunsets - Shakin' Stevens And The Sunsets",
    genre: "Rock & Roll",
    media: "Very Good+",
    sleeve: "Very Good",
    price: "£1.99",
  },
  {
    id: 13,
    img: "https://i.discogs.com/RO04Zr0gK95cXYaJ3tDnDgj3j46E6QkZlSKUHykjxXY/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3NjMx/MC0xNTExNzE1MjM5/LTY3NzEuanBlZw.jpeg",
    link: "https://www.discogs.com/sell/item/3361454538?ev=bp_det",
    desc: "Michael Jackson And Diana Ross - Love Songs",
    genre: "Funk & Soul",
    media: "Very Good+",
    sleeve: "Very Good",
    price: "£2.22",
  },
  {
    id: 14,
    img: "https://i.discogs.com/hmhEXTXoFyK6EOQsurmkp6e_eJK9jRXYAqTSEkOFlQ8/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExNDQz/NTUtMTI5NjczNjA3/NC5qcGVn.jpeg",
    link: "https://www.discogs.com/sell/item/3361453377?ev=bp_det",
    desc: "Stiff Little Fingers - Nobody's Heroes",
    genre: "Punk",
    media: "Very Good",
    sleeve: "Very Good+",
    price: "£19.99",
  },
  {
    id: 15,
    img: "https://i.discogs.com/AaxubAHJor5e3XgZaDqCQFLPrCHbuDUy5voldoHdGeY/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM0MDQ4/NzMtMTY1MzQ3Nzg2/NC05MTk0LmpwZWc.jpeg",
    link: "https://www.discogs.com/sell/item/3361451739?ev=bp_det",
    desc: "The Shadows - At Their Very Best",
    genre: "Pop Rock",
    media: "Near Mint",
    sleeve: "Very Good+",
    price: "£3.90",
  },
  {
    id: 16,
    img: "https://i.discogs.com/uMF0FOiy7TLNFZ7U1HFsv80femAebMI54b27zlLPL-I/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI5NjYy/MjU4LTE3MDY3ODky/NDctOTc0NC5qcGVn.jpeg",
    link: "https://www.discogs.com/sell/item/3361451739?ev=bp_det",
    desc: "Donna Summer - Another Place And Time",
    genre: "Disco",
    media: "Very Good+",
    sleeve: "Very Good+",
    price: "£8.50",
  },
  {
    id: 17,
    img: "https://i.discogs.com/4sc5vxRKd-0Rx4r4odp8VeU43opuKtFcHsFiCVkYW8Y/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE5NzYy/Ny0xNTkwOTE1NzQx/LTgwNjEuanBlZw.jpeg",
    link: "https://www.discogs.com/sell/cart/?add=3348394464&ev=",
    desc: "Thompson Twins - Hold Me Now",
    genre: "Synth Pop",
    media: "Near Mint",
    sleeve: "Very Good+",
    price: "£3.90",
  },
  {
    id: 18,
    img: "https://i.discogs.com/3JBeEEo82Tk44HKCFT-gKcz7RLY9sQUB8w0gnkNpfBQ/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE0NzYz/Ny0xNTA4Nzc1MTMz/LTQwMzIuanBlZw.jpeg",
    link: "https://www.discogs.com/sell/item/3346868010?ev=bp_det",
    desc: "Visage - The Damned Don't Cry",
    genre: "Synth Pop",
    media: "Very Good+",
    sleeve: "Very Good",
    price: "£3.99",
  },
  {
    id: 19,
    img: "https://i.discogs.com/JvvNBMzS5NqN1_4RaoMHGh2DZ5Cb0gioNJo3qY8ojoU/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMzOTAx/OS0xNDI3NzgzNzM2/LTEyMDQuanBlZw.jpeg",
    link: "https://www.discogs.com/sell/cart/?add=3336946239&ev=",
    desc: "Janet Jackson - Control",
    genre: "Funk & Soul",
    media: "Near Mint",
    sleeve: "Very Good+",
    price: "£7.50",
  },
  {
    id: 20,
    img: "https://i.discogs.com/sKHGgbwJE2NuK5IZpIdNPPeMu8GlgiyR-xQhRVw2XK8/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE2MDA5/NzIyLTE2MDE4MTk0/NDMtNTQyMi5qcGVn.jpeg",
    link: "https://www.discogs.com/sell/cart/?add=3336943359&ev=",
    desc: "Hoyt Axton - Less Than The Song",
    genre: "Folk",
    media: "Very Good+",
    sleeve: "Good+",
    price: "£3.00",
  },
  {
    id: 21,
    img: "https://i.discogs.com/FwjichAUJQKBMrxTZJO_qHeCHVlUbUwJR3QjRyEeOxE/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTUzMDY4/ODUtMTM5MzU4OTI3/MC03ODA3LmpwZWc.jpeg",
    link: "https://www.discogs.com/sell/cart/?add=3331621044&ev=",
    desc: "Hawkwind - Sonic Attack",
    genre: "Psychodelic Rock",
    media: "Near Mint",
    sleeve: "Near Mint",
    price: "£35.00",
  },
  {
    id: 22,
    img: "https://i.discogs.com/C3JFEV8zrWNQ4MCTz7ef01y_v96Jh_VU5kDkx99A5tY/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwNzg3/NDMtMTE5MTc1Njcz/Ny5qcGVn.jpeg",
    link: "https://www.discogs.com/sell/cart/?add=3331001625&ev=",
    desc: "Dead Kennedys - Give Me Convenience Or Give Me Death",
    genre: "Punk",
    media: "Very Good+",
    sleeve: "Very Good+",
    price: "£35.50",
  },
  {
    id: 23,
    img: "https://i.discogs.com/Xsd-HT64X4ptweCFN4DBgA217S7TmAhuGuP6K1lOYXY/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExMTY3/MTQtMTUyODEyODU1/Ni05NzY2LmpwZWc.jpeg",
    link: "https://www.discogs.com/sell/cart/?add=3330975777&ev=",
    desc: "God (6) - For Lovers Only",
    genre: "Punk",
    media: "Very Good",
    sleeve: "Very Good",
    price: "£12.50",
  },
  {
    id: 24,
    img: "https://i.discogs.com/xCgI7gQKGanIkLbRJvLi3wMFWErk6eBrRQl8AbFpbjk/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI1NjYw/NzctMTI5Njc2MjM4/My5qcGVn.jpeg",
    link: "https://www.discogs.com/sell/cart/?add=3330971133&ev=",
    desc: "The Specials - More Specials",
    genre: "Ska & Raggae",
    media: "Very Good",
    sleeve: "Very Good",
    price: "£14.50",
  },
  {
    id: 25,
    img: "https://i.discogs.com/bt3U7jBlEf1UChyzOeozzW28pzMTP_YQ-P6ohJHee7c/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTkxNzI5/NDQtMTQ3NjA0MzMx/OS0yNjM3LmpwZWc.jpeg",
    link: "https://www.discogs.com/sell/cart/?add=3330965166&ev=",
    desc: "The Incredible String Band - The Big Huge",
    genre: "Psychodelic Rock",
    media: "Very Good+",
    sleeve: "Very Good",
    price: "£11.00",
  },
  {
    id: 26,
    img: "https://i.discogs.com/3cTMym3kzjbbLMUtx7jrDfCK-0p55zhxVugODmFNx_Y/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM4NTg2/My0xMTg4NjY2MjI3/LmpwZWc.jpeg",
    link: "https://www.discogs.com/sell/cart/?add=3330962295&ev=",
    desc: "Blitz (3) - Voice Of A Generation",
    genre: "Punk",
    media: "Very Good",
    sleeve: "Very Good",
    price: "£30.00",
  },
  {
    id: 27,
    img: "https://i.discogs.com/rJgVfdX1T40whzvFte_ejtzxKC1P5oRHIMs9-uNygro/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM0NTE2/My0xMzQ1MjM5MDEw/LTgwMDQuanBlZw.jpeg",
    link: "https://www.discogs.com/sell/cart/?add=3330959664&ev=",
    desc: "Skids - Days In Europa",
    genre: "Punk",
    media: "Very Good+",
    sleeve: "Very Good",
    price: "£14.50",
  },
  {
    id: 28,
    img: "https://i.discogs.com/jtXvF3L_qmgnU0bX3mq6YQ1nNdcV7TDMqn1lgBl4qfw/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE3NzEz/MzQtMTI5NDE1MzY3/OS5qcGVn.jpeg",
    link: "https://www.discogs.com/sell/cart/?add=3330957450&ev=",
    desc: "Dead Kennedys - Plastic Surgery Disasters",
    genre: "Punk",
    media: "Very Good+",
    sleeve: "Very Good",
    price: "£50.00",
  },
  {
    id: 29,
    img: "https://i.discogs.com/vcfz7JGx58dS8Cd4W9ixGYOKKxeOvVDwpgedGIP5Kno/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTgyMzk5/OS0xMzQxMjYxOTQz/LTQwNzguanBlZw.jpeg",
    link: "https://www.discogs.com/sell/cart/?add=3330955656&ev=",
    desc: "Sore Throat - Unhindered By Talent",
    genre: "Punk",
    media: "Very Good",
    sleeve: "Very Good",
    price: "£70.00",
  },
  {
    id: 30,
    img: "https://i.discogs.com/Gel__zzFgrQhs0wo4ltGRzWeSVF4a-le2E3AqtG5cjg/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTc3MzQ1/MS0xNDc2MTg4MTUy/LTk4NTUuanBlZw.jpeg",
    link: "https://www.discogs.com/sell/cart/?add=3325401075&ev=",
    desc: "Dr. Feelgood - Stupidity",
    genre: "Blues",
    media: "Very Good",
    sleeve: "Very Good",
    price: "£8.99",
  },
  {
    id: 31,
    img: "https://i.discogs.com/YrRAB3sLmQvoJFjwJbwbpxcEPHw2RcTsd3emgC2C8P4/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIyNDM4/MjItMTQ5MDUzOTUx/Ny01NDk4LmpwZWc.jpeg",
    link: "https://www.discogs.com/sell/cart/?add=3322521063&ev=",
    desc: "Various - This Is Oi! (A Streetpunk Compilation)",
    genre: "Punk",
    media: "Very Good+",
    sleeve: "Very Good",
    price: "£35.00",
  },
  {
    id: 32,
    img: "https://i.discogs.com/ffDsyPIcQWemIP0JdF4unc5zXm8iGRmfmApjOhEgzmE/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM4ODIz/OC0xNDk5NTY1MTc3/LTE0MTEuanBlZw.jpeg",
    link: "https://www.discogs.com/sell/cart/?add=3322515288&ev=",
    desc: "Siouxsie And The Banshees - Dear Prudence",
    genre: "Psychodelic Rock",
    media: "Near Mint",
    sleeve: "Very Good+",
    price: "£25.00",
  },
];
